{
 "title": "Slurm Cluster Health",
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "user_name",
    "label": "Job User Name",
    "query": {
     "query": "label_values(slurm_job_info, user_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Slurm Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes by State",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (state_base) (slurm_node_info)",
     "legendFormat": "{{state_base}}"
    }
   ]
  },
  {
   "title": "Node Problems",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node_name, state_base) (slurm_node_info{state_base=~\"DOWN|ERROR\", state_is_drain=\"false\"})",
     "legendFormat": "{{node_name}}, {{state_base}}"
    },
    {
     "expr": "sum by (node_name, state_base) (slurm_node_info{state_is_drain=\"true\"})",
     "legendFormat": "{{node_name}}, {{state_base}}+DRAIN"
    }
   ]
  },
  {
   "title": "Node Problems Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "(slurm_node_info{state_base=~\"DOWN|ERROR\", state_is_drain=\"false\"} or slurm_node_info{state_is_drain=\"true\"}) * on(node_name) group_left(reason) (slurm_node_fails_total or on(node_name) (slurm_node_info * 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Problems Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (node_name) (\n  count by (node_name) (slurm_node_info{state_is_drain=\"true\", state_base!=\"DOWN\"}) * 1 or\n  count by (node_name) (slurm_node_info{state_is_drain=\"false\", state_base=\"DOWN\"}) * 2 or\n  count by (node_name) (slurm_node_info{state_is_drain=\"true\", state_base=\"DOWN\"}) * 3\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Slurm Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Non-Terminal Job States",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (job_state, job_id, job_name) (slurm_job_info{job_state=~\".*ING|POWER_UP_NODE|REQUEUE.*|RESV_DEL_HOLD|STAGE_OUT|STOPPED|SUSPENDED|UPDATE_DB\", user_name=~\"$user_name\"})",
     "legendFormat": "{{job_id}}: {{job_state}}, {{job_name}}"
    }
   ]
  },
  {
   "title": "Job State Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_join(\n  sum by (job_id, job_name)(\n    count by (job_id, job_name) (slurm_job_info{job_state=\"PENDING\", user_name=~\"$user_name\"}) * 1 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"CONFIGURING\", user_name=~\"$user_name\"}) * 2 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"RUNNING\", user_name=~\"$user_name\"}) * 3 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"COMPLETING\", user_name=~\"$user_name\"}) * 4 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"COMPLETED\", user_name=~\"$user_name\"}) * 5 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"CANCELLED\", user_name=~\"$user_name\"}) * 6 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"FAILED\", user_name=~\"$user_name\"}) * 7 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"TIMEOUT\", user_name=~\"$user_name\"}) * 8 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"PREEMPTED\", user_name=~\"$user_name\"}) * 9 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"NODE_FAIL\", user_name=~\"$user_name\"}) * 10 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"BOOT_FAIL\", user_name=~\"$user_name\"}) * 11 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"DEADLINE\", user_name=~\"$user_name\"}) * 12 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"OUT_OF_MEMORY\", user_name=~\"$user_name\"}) * 13 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"REQUEUED\", user_name=~\"$user_name\"}) * 14 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"RESIZING\", user_name=~\"$user_name\"}) * 15 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"SUSPENDED\", user_name=~\"$user_name\"}) * 16 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"STOPPED\", user_name=~\"$user_name\"}) * 17 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"POWER_UP_NODE\", user_name=~\"$user_name\"}) * 18 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"SIGNALING\", user_name=~\"$user_name\"}) * 19 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"STAGE_OUT\", user_name=~\"$user_name\"}) * 20 or\n    count by (job_id, job_name) (slurm_job_info{job_state=\"UPDATE_DB\", user_name=~\"$user_name\"}) * 21\n  ),\n  \"job_display\", \": \", \"job_id\", \"job_name\"\n)",
     "legendFormat": "{{job_display}}"
    }
   ]
  }
 ]
}