{
 "title": "Pod metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=\"$pod\", image!~\".*pause:.*$\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace(s) CPU Usage in cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", unit=\"core\"})",
     "legendFormat": "Requests (deployments)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", unit=\"core\"})",
     "legendFormat": "Limits (deployments)"
    },
    {
     "expr": "kube_resourcequota{namespace=~\"$namespace\", resource=\"requests.cpu\",type=\"hard\"}",
     "legendFormat": "Requests (quotas)"
    },
    {
     "expr": "kube_resourcequota{namespace=~\"$namespace\", resource=\"limits.cpu\",type=\"hard\"}",
     "legendFormat": "Limits  (quotas)"
    }
   ]
  },
  {
   "title": "Namespace(s) CPU Usage Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", unit=\"byte\"})",
     "legendFormat": "Requests (deployments)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", unit=\"byte\"})",
     "legendFormat": "Limits (deployments)"
    },
    {
     "expr": "kube_resourcequota{namespace=~\"$namespace\", resource=\"requests.memory\",type=\"hard\"}",
     "legendFormat": "Requests (quotas)"
    },
    {
     "expr": "kube_resourcequota{namespace=~\"$namespace\", resource=\"limits.memory\",type=\"hard\"}",
     "legendFormat": "Limits (quotas)"
    }
   ]
  },
  {
   "title": "CPU Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max (rate(container_cpu_usage_seconds_total{image!=\"\", image!~\".*pause:.*$\", namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max (kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "max (kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max (rate(container_cpu_usage_seconds_total{image!=\"\", image!~\"^k8s.gcr.io/pause:.*$\", namespace=\"$namespace\", pod=\"$pod\"}[5m]))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "requests"
    },
    {
     "expr": "max (kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "limits"
    },
    {
     "expr": "max (container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Throttling containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*sum by (pod, namespace)(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"}[5m]))/\nsum by (pod, namespace)(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\",pod=\"$pod\", container=\"$container\"}[5m]))",
     "legendFormat": "{{ pod }} {{ container }}"
    }
   ]
  },
  {
   "title": "Resource used on Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"$namespace\"})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{namespace=\"$namespace\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_ingress_info{namespace=\"$namespace\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{namespace=\"$namespace\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{namespace=\"$namespace\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{namespace=\"$namespace\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{namespace=~\"$namespace\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{namespace=\"$namespace\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{namespace=\"$namespace\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{namespace=~\"$namespace\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{namespace=\"$namespace\"})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "sum(kube_job_labels{namespace=\"$namespace\"})",
     "legendFormat": "jobs"
    },
    {
     "expr": "sum(kube_cronjob_labels{namespace=\"$namespace\"})",
     "legendFormat": "cronjob"
    }
   ]
  },
  {
   "title": "container restarts total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{container}}  {{reason}}"
    }
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{image!=\"\",namespace=\"$namespace\"}[1m]) * 8",
     "legendFormat": "receive -> {{ pod }}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{image!=\"\",namespace=\"$namespace\"}[1m]) * -8",
     "legendFormat": "transmit <- {{ pod }}"
    }
   ]
  }
 ]
}