name: "Soperator Terraform"

on:
  pull_request:
    paths:
      - "soperator/**"
  push:
    branches:
      - main
    paths:
      - "soperator/**"

permissions:
  contents: read

jobs:
  markdown-lint:
    name: "Soperator Markdown lint"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: soperator

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Markdown lint - All README.md files inside Soperator module
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        continue-on-error: true
        with:
          config: 'soperator/.markdownlint.yaml'
          fix: false
          globs: |
            soperator/README.md
            soperator/modules/weka/README.md
            soperator/test/README.md
            soperator/test/quickcheck/README.md

  terraform-check:
    name: "Soperator Terraform Checks"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: soperator

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "v1.12.2"
          terraform_wrapper: false

      # fmt check + init/validate of all modules and installations + module tests
      - name: Terraform Check - Modules and Installations
        run: make terraform-check
